
# Generated by Django 4.1.1 on 2022-11-25 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(default='', max_length=500)),
                ('outfit_info', models.CharField(max_length=500)),
                ('popularity', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('image_link', models.CharField(max_length=500)),
                ('purchase_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image_link', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('dates', models.TextField(blank=True)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cloth', to='ooo.closet')),
                ('label_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cloth', to='ooo.labelset')),
            ],
        ),
        migrations.CreateModel(
            name='SampleCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('image_link', models.CharField(max_length=500)),
                ('purchase_link', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('label_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_cloth', to='ooo.labelset')),
                ('outfit', models.ManyToManyField(related_name='sample_cloth', to='ooo.outfit')),
            ],
        ),
    ]
