# Generated by Django 4.1.1 on 2022-10-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
