# Generated by Django 4.1.1 on 2022-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ooo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercloth",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="images/"),
        ),
    ]
