# Generated by Django 4.1.1 on 2022-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooo', '0004_usercloth_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercloth',
            name='dates',
            field=models.TextField(default='[]'),
        ),
    ]
