# Generated by Django 4.1.1 on 2022-11-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ooo", "0004_usercloth_dates"),
    ]

    operations = [
        migrations.RemoveField(model_name="samplecloth", name="outfit",),
        migrations.AlterField(
            model_name="usercloth", name="dates", field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="samplecloth",
            name="outfit",
            field=models.ManyToManyField(related_name="sample_cloth", to="ooo.outfit"),
        ),
    ]
