# Generated by Django 4.1.1 on 2022-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ooo", "0006_remove_outfit_image_id_remove_samplecloth_image_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercloth", name="dates", field=models.TextField(default='""'),
        ),
    ]
