# Generated by Django 4.1.1 on 2022-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ooo", "0010_alter_usercloth_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplecloth",
            name="outfit",
            field=models.ManyToManyField(
                blank=True, related_name="sample_cloth", to="ooo.outfit"
            ),
        ),
    ]
