# Generated by Django 4.1.1 on 2022-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooo', '0010_alter_usercloth_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercloth',
            name='image_link',
        ),
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='outfit_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='samplecloth',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='usercloth',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='outfit_info',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='samplecloth',
            name='image_link',
            field=models.CharField(max_length=500),
        ),
    ]
