# Generated by Django 4.1.1 on 2022-11-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooo', '0005_alter_usercloth_dates'),
        ('ooo', '0011_alter_samplecloth_outfit'),
    ]

    operations = [
    ]
